---
# https://github.com/IntelRealSense/realsense-ros/blob/ros2-master/README.md#published-topics
  - topic_name: <robot_namespace><device_namespace>/color/camera_info
    ros_type_name: sensor_msgs/msg/CameraInfo
    gz_type_name: ignition.msgs.CameraInfo
    lazy: true

  - topic_name: <robot_namespace><device_namespace>/color/image_raw
    ros_type_name: sensor_msgs/msg/Image
    gz_type_name: ignition.msgs.Image
    lazy: true

  - topic_name: <robot_namespace><device_namespace>/depth/camera_info
    ros_type_name: sensor_msgs/msg/CameraInfo
    gz_type_name: ignition.msgs.CameraInfo
    lazy: true

  - topic_name: <robot_namespace><device_namespace>/depth/image_rect_raw
    ros_type_name: sensor_msgs/msg/Image
    gz_type_name: ignition.msgs.Image
    lazy: true

  - ros_topic_name: <robot_namespace><device_namespace>/depth/color/points
    gz_topic_name: <robot_namespace><device_namespace>/depth/image_rect_raw/points
    ros_type_name: sensor_msgs/msg/PointCloud2
    gz_type_name: ignition.msgs.PointCloudPacked
    lazy: true